### ISSUE TITLE
Form UI requirements

### ISSUE THREAD

**Issue by igorbandurovych** [bohdanMm/RubberDuck2#5]
Development UI requirements for the project: wireframes, clickable prototypes, mockups. (Balsamiq, Invision, Figma)
**Results:** UI requirements in the form of wireframes, clickable prototypes, Mockups

**Comment by VasylynaTarnavska** [comment]
https://www.figma.com/file/FBDnTqn5l0sNcj6UHbosyK/Just-eat-it!?node-id=0%3A1&t=DC0DKcMbAGP7cLgX-1

**Comment by VasylynaTarnavska** [comment]
https://www.figma.com/proto/FBDnTqn5l0sNcj6UHbosyK/Just-eat-it!?node-id=225-1240&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=5%3A95
